name: Add Labels on Issue Create

on:
  issues:
    types:
      - opened

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Add labels
        run: |
          echo "Creating a new issue. Adding 'hacktoberfest' and 'hacktoberfest2023' labels."
          # Use GitHub API to add the labels
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"labels":["hacktoberfest", "hacktoberfest2023"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels"
