
name: Add Label on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged
        id: pr-merged
        run: echo "::set-output name=merged::${{ github.event.pull_request.merged }}"

      - name: Add label
        if: steps.pr-merged.outputs.merged == 'true'
        run: |
          echo "Merging PR. Adding 'hacktoberfest-accepted' label."
          # Use GitHub API to add the label
          curl -X POST -H "Authorization: token ${{ secrets.VIVEK_TOKEN }}" \
            -d '{"labels":["hacktoberfest-accepted"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"
